---
title: "Simulation_500 mg"
output: html_document
date: today
---

```{r setup, include=FALSE}
library(tidyverse)

simData <- data.table::fread("single_dose.csv")


sim_full <-  simData%>% 
  filter(evid == 0)



obsTime <- c(
  0, 0.02, 0.08, 0.2, 0.3, 0.5, 1.0, 2.0, 3.0, 7.0, 14.0, 21, 28, 35, 42
)


viralData <-  c(
  0.02, 0.08, 0.2, 0.3, 0.5)

```



```{r}

upDated <-  simData %>% 
  
  select(id,time,Concentration,Virus,DV,evid,amt,cmt,rate,route,tad,dosenum, Dose) %>% 
  
  mutate(Concentration = ifelse(Concentration <= 0, NA, Concentration)) %>% 
  
  mutate(iDV = ifelse(time %in% viralData, NA, DV)) %>% 
  
  mutate(FLG = ifelse(iDV > 0 | amt>0, 2, 1)) %>% 
  mutate(FLG = ifelse(is.na(FLG), 1, FLG))


write.csv(file="hiv_d1.csv", upDated, row.names = F,
na = "")

```




```{r}
df_pre <-  sim_full %>% 
  select(id, time, Conc = Concentration, Virus, DV,  Central:AUC, Dose) %>% 
  mutate(amt = as.numeric(str_extract(Dose, "^\\d+"))) %>% 
  mutate(Dose = factor(Dose, levels = c("20 mg per day",
                                        "40 mg per day",
                                        "80 mg per day",
                                        "120 mg every day",
                                        "850 mg every week",
                                        "900 mg single dose")))
```


```{r pk_avg}
## Calculate summary statistics
minprobs=0.25
maxprobs=0.75

sum_stat <- df_pre %>%
  group_by(time, amt) %>%
  reframe( Dose = Dose,
    Median_C=median(Conc),
            Low_percentile=quantile(Conc,probs=minprobs),
            High_percentile=quantile(Conc,probs=maxprobs)
  )  
```



```{r pkAvgplot, echo=FALSE, fig.height=8, fig.width=11}
ggplot(sum_stat, aes(x=time,y=Median_C, group =amt, fill = Dose)) +
  
  ## Add ribbon for variability
  geom_ribbon(aes(ymin=Low_percentile, ymax=High_percentile, x=time), alpha = 0.15, linetype=0)+
  
  ## Add median line
  geom_line(size=2) +
  
  # scale_y_log10()+
  
  # Set axis and theme
  theme_bw()+
  theme(legend.position="none")+
  # scale_y_log10()+
  labs(y = "Concentration (ng/mL)",
       x = "Time (Days)", 
       fill = "Dose (mg)",
       caption = "\n Median concentration with 95% PI around median
                  \n vertical red line: 850 ng/mL
                  \n At end of the 5th day from dosing, 850mg/week has Ctrough < 850ng/mL",
       title = "Comparison of exposure metrics between different doses",
       subtitle = "Based on one simulation with 500 subjects/Dose level")+
  theme_bw() +
  theme(
    plot.title = element_text(size = 18, face = "bold"),  # Increase title size
    axis.title.x = element_text(size = 14),             # Increase x-axis label size
    axis.title.y = element_text(size = 14),             # Increase y-axis label size
    axis.text = element_text(size = 12)                 # Increase tick label size
  )+
  geom_hline(aes(yintercept = 850), color = "indianred", linewidth = 1, linetype = 2)
```


## PD Plots


```{r PDcalculations}
options(scipen = 99999)

df_pre <-  sim_full %>% 
  select(id, time, Conc = Concentration, Virus, DV,  Central:AUC, Dose) %>% 
  mutate(amt = as.numeric(str_extract(Dose, "^\\d+"))) %>% 
  mutate(Dose = factor(Dose, levels = c("20 mg per day",
                                        "40 mg per day",
                                        "80 mg per day",
                                        "120 mg every day",
                                        "850 mg every week",
                                        "900 mg single dose")))

bsl <- df_pre %>% 
  filter(time==0) %>% 
  mutate(V0 = Virus) %>% 
  select(id, V0)

df <- df_pre %>% 
  left_join(bsl) %>% 
  mutate(CHB = Virus-V0,
    RCHB = 100*(Virus-V0)/V0) %>% 
  mutate(RCHB = signif(RCHB, digits = 2))


propT <- df_pre %>% 
  mutate(TargetYes = ifelse(Virus<1.69, "Yes", "No")) %>% 
  filter(TargetYes == "No") %>% 
  group_by(Dose,time,TargetYes) %>% 
  reframe(nSub = n()) %>% 
  mutate(Perc = 100-(100*(nSub/100)))

sum_stat_res <- df %>%
  group_by(time, amt) %>%
  reframe( Dose = Dose,
           Median_R=median(CHB),
           Low_percentile=quantile(CHB,probs=minprobs),
           High_percentile=quantile(CHB,probs=maxprobs)
  )

sum_stat_dv <- df %>%
  group_by(time, amt) %>%
  reframe( Dose = Dose,
           Median_R=median(Virus),
           Low_percentile=quantile(Virus,probs=minprobs),
           High_percentile=quantile(Virus,probs=maxprobs)
  )
```




```{r echo=FALSE, fig.height=8, fig.width=11}
ggplot(sum_stat_res, aes(x=time,y=Median_R, group = amt)) +
  
  ## Add ribbon for variability
  # geom_ribbon(aes(ymin=Low_percentile, ymax=High_percentile, x=time, fill = Dose), 
  #             alpha = 0.15, linetype=0, show.legend = F)+
  
  ## Add median line
  geom_line(size=2, aes(color = Dose)) +
  theme_bw()+
  theme(legend.position="none")+
  labs(y = "Change from baseline",
       x = "Time (Days)", 
       fill = "Dose (mg)",
       caption = "\n Median response with 95% PI around median",
       title = "Comparison of Response between different doses",
       subtitle = "Based on one simulation with 500 subjects/Dose level")+
  theme_bw() +
  theme(
    plot.title = element_text(size = 18, face = "bold"),  # Increase title size
    axis.title.x = element_text(size = 14),             # Increase x-axis label size
    axis.title.y = element_text(size = 14),             # Increase y-axis label size
    axis.text = element_text(size = 12)                 # Increase tick label size
  )

```




```{r echo=FALSE, fig.height=8, fig.width=11}
ggplot(sum_stat_res, aes(x=time,y=Median_R, group = amt)) +
  
  ## Add ribbon for variability
  geom_ribbon(aes(ymin=Low_percentile, ymax=High_percentile, x=time, fill = Dose),
              alpha = 0.15, linetype=0, show.legend = F)+
  
  ## Add median line
  geom_line(size=2, aes(color = Dose)) +
  theme_bw()+
  theme(legend.position="none")+
  labs(y = "Change from baseline",
       x = "Time (Days)", 
       fill = "Dose (mg)",
       caption = "\n Median response with 95% PI around median",
       title = "Comparison of Response between different doses",
       subtitle = "Based on one simulation with 500 subjects/Dose level")+
  theme_bw() +
  theme(
    plot.title = element_text(size = 18, face = "bold"),  # Increase title size
    axis.title.x = element_text(size = 14),             # Increase x-axis label size
    axis.title.y = element_text(size = 14),             # Increase y-axis label size
    axis.text = element_text(size = 12)                 # Increase tick label size
  )+
  facet_wrap(. ~ Dose)

```




```{r echo=FALSE, fig.height=8, fig.width=11}

ggplot(propT, aes(x=time,y=Perc, group = Dose)) +
  
  ## Add ribbon for variability
  # geom_ribbon(aes(ymin=Low_percentile, ymax=High_percentile, x=time, fill = Dose), 
  #             alpha = 0.15, linetype=0, show.legend = F)+
  
  ## Add median line
  geom_line(size=2, aes(color = Dose)) +
  theme_bw()+
  theme(legend.position="none")+
  labs(y = "Proportion of subjects HIV RNA <50 c/mL",
       x = "Time (Days)", 
       fill = "Dose (mg)",
       caption = "\n Median response with 95% PI around median",
       title = "Comparison of Response between different doses",
       subtitle = "Based on one simulation with 500 subjects/Dose level",
  )+
  theme_bw() +
  ylim(0,105)+
  theme(
    plot.title = element_text(size = 18, face = "bold"),  # Increase title size
    axis.title.x = element_text(size = 14),             # Increase x-axis label size
    axis.title.y = element_text(size = 14),             # Increase y-axis label size
    axis.text = element_text(size = 12)                 # Increase tick label size
  )
```



```{r echo=FALSE, fig.height=8, fig.width=11}
ggplot(sum_stat_dv, aes(x=time,y=Median_R, group = amt)) +
  
  ## Add ribbon for variability
  # geom_ribbon(aes(ymin=Low_percentile, ymax=High_percentile, x=time, fill = Dose), 
  #             alpha = 0.15, linetype=0, show.legend = F)+
  
  ## Add median line
  geom_line(size=2, aes(color = Dose)) +
  theme_bw()+
  theme(legend.position="none")+
  labs(y = "HIV RNA log10(copies/mL)",
       x = "Time (Days)", 
       fill = "Dose (mg)",
       caption = "\n Median response with 95% PI around median
                  \n Vertical red line: 50copies/mL",
       title = "Comparison of Response between different doses",
       subtitle = "Based on one simulation with 500 subjects/Dose level")+
  theme_bw() +
  theme(
    plot.title = element_text(size = 18, face = "bold"),  # Increase title size
    axis.title.x = element_text(size = 14),             # Increase x-axis label size
    axis.title.y = element_text(size = 14),             # Increase y-axis label size
    axis.text = element_text(size = 12)                 # Increase tick label size
  )+
  geom_hline(aes(yintercept = 1.7), color = "indianred", linewidth = 1, linetype = 2)

```



```{r echo=FALSE, fig.height=8, fig.width=11}
ggplot(sum_stat_dv, aes(x=time,y=Median_R, group = amt)) +
  
  ## Add ribbon for variability
  geom_ribbon(aes(ymin=Low_percentile, ymax=High_percentile, x=time, fill = Dose),
              alpha = 0.15, linetype=0, show.legend = F)+
  
  ## Add median line
  geom_line(size=2, aes(color = Dose)) +
  theme_bw()+
  theme(legend.position="none")+
  labs(y = "HIV RNA log10(copies/mL)",
       x = "Time (Days)", 
       fill = "Dose (mg)",
       caption = "\n Median response with 95% PI around median
                  \n Vertical red line: 50copies/mL",
       title = "Comparison of Response between different doses",
       subtitle = "Based on one simulation with 500 subjects/Dose level")+
  theme_bw() +
  theme(
    plot.title = element_text(size = 18, face = "bold"),  # Increase title size
    axis.title.x = element_text(size = 14),             # Increase x-axis label size
    axis.title.y = element_text(size = 14),             # Increase y-axis label size
    axis.text = element_text(size = 12)                 # Increase tick label size
  )+
  facet_wrap(. ~ Dose)+
  geom_hline(aes(yintercept = 1.7), color = "indianred", linewidth = 1, linetype = 2)

```
